/***********************************************************************/
/*                                                                     */
/*  FILE        :hwsetup.c                                             */
/*  DATE        :Wed, Jan 28, 2009                                     */
/*  DESCRIPTION :Hardware Setup file                                   */
/*  CPU TYPE    :Other                                                 */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.13).    */
/*                                                                     */
/***********************************************************************/
/* Mar 22 '10  REA   For RX62N with new CAN API.*/

#include "iodefine.h"
#include "rskRX62Ndef.h"
#include "stdint.h"
#include "r_can_api.h"
	
#ifdef __cplusplus
extern "C" {
#endif
extern void HardwareSetup(void);
#ifdef __cplusplus
}
#endif

static void PeripheralStandbyControl(void);

/******************************************************************************
Function Name:       HardwareSetup
Parameters:          -
Return value:        -
Description:         IO and peripheral control.
******************************************************************************/
void HardwareSetup(void)
{
	/* ICLK = EXTAL*8 = 12M*8 = 96 MHz. */
	SYSTEM.SCKCR.BIT.ICK  =  0;
	/* PCLK = EXTAL*4 = 12M*4 = 48 MHz. */
	SYSTEM.SCKCR.BIT.PCK  =  1;
	/* BCLK = EXTAL*2 = 12M*2 = 24 MHz. */
	SYSTEM.SCKCR.BIT.BCK  =  2;
	/* Enable BCLK output (high level). */
	SYSTEM.SCKCR.BIT.PSTOP1  =  0;	
	
	/* BCLK output (24MHz). */
	/* P5.DDR.BIT.B3  =  1;
    
		
	/*** DEFAULT port settings. Configure as output low. ***/
	/* Port0. */
	PORT1.DDR.BYTE = 0xFF;
	PORT1.DR.BYTE = 0x00;
	/* Port1. */
	PORT1.DDR.BYTE = 0xFF;
	PORT1.DR.BYTE = 0x00;
	/* Port2. */
	PORT2.DDR.BYTE = 0xFF;
	PORT2.DR.BYTE = 0x00;
	/* Port3. */
	PORT3.DDR.BYTE = 0xFF;
	PORT3.DR.BYTE = 0x00;
	/* Port4. */
	PORT4.DDR.BYTE = 0xFF;
	PORT4.DR.BYTE = 0x00;
	/* Port5. */
	PORT5.DDR.BYTE = 0xFF;
	PORT5.DR.BYTE = 0x00;
	/* Port6. */
	PORT6.DDR.BYTE = 0xFF;
	PORT6.DR.BYTE = 0x00;
	/* Port7. */
	PORT7.DDR.BYTE = 0xFF;
	PORT7.DR.BYTE = 0x00;
	/* Port8 */
	PORT8.DDR.BYTE = 0xFF;
	PORT8.DR.BYTE = 0x00;
	/* Port9. */
	PORT7.DDR.BYTE = 0xFF;
	PORT7.DR.BYTE = 0x00;
	
	
	/*** SPECIFIC port settings. ***/
	/* Switches are inputs. 
	SW1 is p0_0, SW2 is p0_1, SW3 is p0_7. */
	PORT0.DDR.BIT.B0 = 0;
	PORT0.DDR.BIT.B1 = 0;
	PORT0.DDR.BIT.B7 = 0;		

	/* Switches; set ICR for P0_0, 1, and 7. */
	PORT0.ICR.BIT.B0 = 1;
	PORT0.ICR.BIT.B1 = 1;
	PORT0.ICR.BIT.B7 = 1;
	
	/* Set LCD pins as outputs. */
    /* LCD-RS. */
    PORT8.DDR.BIT.B4  =  1;
    /* LCD-EN. */
    PORT8.DDR.BIT.B5  =  1;
    /* LCD-data. */
    PORT9.DDR.BYTE  =  0xF0;
	
	/* Set LED ports as outputs. */
	ENABLE_LEDS
    ALL_LEDS_ON
	
	/* For CAN see API. Set default port for CAN so an output high on a 
    CAN pin or low doesn't affect the bus. */
	R_CAN_PortSet(0, ENABLE);
    
	PeripheralStandbyControl();
}/* HardwareSetup() */

/******************************************************************************
Function Name:       PeripheralStandbyControl
Parameters:          -
Return value:        -
Description:         Control whether peripherals are in standby or is on.
******************************************************************************/
static void PeripheralStandbyControl(void)
{
	/* CAN: Module Stop Control Register B (MSTPCRB) bit0 is for CAN Module.
	0: The module stop state is canceled.
	1: Transition to the module stop state is made. */
	SYSTEM.MSTPCRB.BIT.MSTPB0  =  0;
	
}/* end PeripheralStandbyControl() */
/* EOF */
