[HIMDBVersion]
2.0
[DATABASE_VERSION]
"1.1" 
[SESSIONS_]
"DefaultSession" 
"SessionRX600_E1_E20_SYSTEM" 
[CONFIGURATIONS]
"Big_Endian" 
"Little_Endian" 
[CURRENT_CONFIGURATION]
"Little_Endian" 
[CURRENT_SESSION]
"DefaultSession" 
[GENERAL_DATA_PROJECT]
"FDT_UserBootAreaFiles" "" 
[GENERAL_DATA_CONFIGURATION_Big_Endian]
"PROJECT_FILES_MODIFIED_DATA_TAG" "FALSE" 
[SESSIONS_Big_Endian]
"DefaultSession" 
"SessionRX600_E1_E20_SYSTEM" 
[GENERAL_DATA_CONFIGURATION_Little_Endian]
"PROJECT_FILES_MODIFIED_DATA_TAG" "FALSE" 
[SESSIONS_Little_Endian]
"DefaultSession" 
"SessionRX600_E1_E20_SYSTEM" 
[GENERAL_DATA_CONFIGURATION_SESSION_Little_Endian_SessionRX600_E1_E20_SYSTEM]
[GENERAL_DATA_SESSION_DefaultSession]
[GENERAL_DATA_CONFIGURATION_SESSION_Big_Endian_SessionRX600_E1_E20_SYSTEM]
[GENERAL_DATA_SESSION_SessionRX600_E1_E20_SYSTEM]
[GENERAL_DATA_CONFIGURATION_SESSION_Little_Endian_DefaultSession]
[GENERAL_DATA_CONFIGURATION_SESSION_Big_Endian_DefaultSession]
[END]
